app_password = "1234"
google_maps_api_key = "AIzaSyD1npPO2oI19D_QEZi_K45dqBG8Y_Ug6WM"
google_gemini_api_key = "AIzaSyBRXoW_kcyYnbs_ETLX421_Dp4a39-uFTI"

[gdrive]
type = "service_account"
project_id = "cityminddriveuploader"
private_key_id = "e8f4e32ffd8f43d0e7ce80082c8797ac529136e6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCrNLI/piFP2UkH
d4ucZRPPxm5Sl9A8/U5lZ49Ss1dxaCyATCt/MFR23bGCVKOilebC5bVvadXnTu+/
+hqF99McTjw9tFbiADRhzVllklgsPsQ1spt/yhqnt7zOeRMa+qq0BqdVZM30uGaC
N/SqBJ96pHU3C9f7q5kH6yNYG1kKYOB24hu0LWXrTPN65tct2aywVulJ2Ljrj9Bd
WhLq7CFAwdecf2x2ABrnSXOyj+AThOTqE0tEOF3GnqS5OXCp6umLc4HKOPMnlzuI
lmhrbi9ylai/3zrGFWLW6Sf6GshDK/dINyhZ2wxcOABGnnhswd+mtHa47PCs+yvw
5nmvAR2FAgMBAAECggEALfuPTG0QUWPoq2q+QpkbQxjmlKRVt6vJHI89/VZRzBHQ
sfzDSfvvE6XjgT++W3KrcflES9I/M0sONZ+08/pl5xpUL7Z6B2VKrGH8+rzdlbSd
+lYoUaA0nItK2KHIMdzVcFjBJLxYXLwSPDNPMULgmo4FNW2m6t9h0LCk44sk1RZT
eaRRQB4qm005p3PdFrgjImQKTKy4qgfZCFgkIIDAYU1Khcj1vcoIg4zx2KvwsMWW
azN9z/HOt2AM3iocLLz3yh8y2PB+hAxmo/o9yoyzMt34nChb5DWVULb1vU88s2o4
MuDRPK/H9hLIO4CpOva6hZ9TZD2uJZbBBrSb28CMmQKBgQDVC2OKqVBK0lEahZdr
iVH8G+C9xZ1iQdcbalzxRYKj3snvjN5GYIGdcHDbIO7MkgiIHfN1GHueuQoP4ofZ
X8XOWl2URsdRJBwR5vO622Guz0vOW6E73Y1/C/CHkyKqqLic432dmI1kv+slnxOb
Od3TuiTlgizHPqW9j68U0DBdSwKBgQDNub458qRnUJoKg39ZVo6ztrWv8SZnsocR
YwRlf4b4xYLNZrI65lir+ztMihk/EZTsmFIV0p5PoV0FQlUsurn4Cb6uEkYJ2TQX
cjW4HCgcO9YBOL37AJgKVGCFWMoR3xzwf6UmYYg6TSvOYBcdI4h8fOy/yhfEn72O
S/VqRoG+bwKBgF8ywJ9Ee0mD45PrYDdAXG9AcdO7C1HNw/ZPOArkGbVqJ2gw1V4z
X5ffl76DX9Hv63oPkCuh7hOF8fYZLsU2o6hK/wfz/LrIXPau8fhscaDwppomncyn
esPrrOaYG+SQkjYg/Y+/jGcZz1S3WcaCPBqRUk1wNtwtpVgobX7qbMIzAoGADNxc
wQCjOHY4ewnHb01S9HcqmoonzXnCqdqXzsSPKoQmbjLKV5ZI2s+E4H8Nnvy5Y6UO
FKErFm1PBGImMvqlX5U0X2tzB3CVqhWQuCbCdylicocakVNzLcoikpN/ZmidRYel
SmX0fziN0YP+TesHwEiLAF5g6ADYd8nV2MP5nm8CgYA08oMSOF2rlsbUsrCMyDV4
Va2bnE627yRA0crtZGPYITdLs/a0fyBGyy1h0nNquHST82vEm2q4dYPyTm9a2NAu
WdSrAKpwoqjYSm0Jr/ptBlk2dn3AbWj+kBZNCJv/pc5YEwBTPB+Pd1ZG+TvVzgVB
qA3VNQYRE8ifm3rau45/zQ==\n-----END PRIVATE KEY-----\n"""
client_email = "citymind-uploader@cityminddriveuploader.iam.gserviceaccount.com"
client_id = "104547591061117576220"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/citymind-uploader%40cityminddriveuploader.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
root_folder_id = "1dDwxQBMfMTBzHMhelp0-_ccF_jzsxobZ"
